package cc.rits.membership.console.iam.infrastructure.db.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class Oauth2RegisteredClientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public Oauth2RegisteredClientExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("`id` like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("`id` not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("`client_id` is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("`client_id` is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(String value) {
            addCriterion("`client_id` =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(String value) {
            addCriterion("`client_id` <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(String value) {
            addCriterion("`client_id` >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("`client_id` >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(String value) {
            addCriterion("`client_id` <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(String value) {
            addCriterion("`client_id` <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLike(String value) {
            addCriterion("`client_id` like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotLike(String value) {
            addCriterion("`client_id` not like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<String> values) {
            addCriterion("`client_id` in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<String> values) {
            addCriterion("`client_id` not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(String value1, String value2) {
            addCriterion("`client_id` between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(String value1, String value2) {
            addCriterion("`client_id` not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtIsNull() {
            addCriterion("`client_id_issued_at` is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtIsNotNull() {
            addCriterion("`client_id_issued_at` is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtEqualTo(LocalDateTime value) {
            addCriterion("`client_id_issued_at` =", value, "clientIdIssuedAt");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtNotEqualTo(LocalDateTime value) {
            addCriterion("`client_id_issued_at` <>", value, "clientIdIssuedAt");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtGreaterThan(LocalDateTime value) {
            addCriterion("`client_id_issued_at` >", value, "clientIdIssuedAt");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`client_id_issued_at` >=", value, "clientIdIssuedAt");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtLessThan(LocalDateTime value) {
            addCriterion("`client_id_issued_at` <", value, "clientIdIssuedAt");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`client_id_issued_at` <=", value, "clientIdIssuedAt");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtIn(List<LocalDateTime> values) {
            addCriterion("`client_id_issued_at` in", values, "clientIdIssuedAt");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtNotIn(List<LocalDateTime> values) {
            addCriterion("`client_id_issued_at` not in", values, "clientIdIssuedAt");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`client_id_issued_at` between", value1, value2, "clientIdIssuedAt");
            return (Criteria) this;
        }

        public Criteria andClientIdIssuedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`client_id_issued_at` not between", value1, value2, "clientIdIssuedAt");
            return (Criteria) this;
        }

        public Criteria andClientSecretIsNull() {
            addCriterion("`client_secret` is null");
            return (Criteria) this;
        }

        public Criteria andClientSecretIsNotNull() {
            addCriterion("`client_secret` is not null");
            return (Criteria) this;
        }

        public Criteria andClientSecretEqualTo(String value) {
            addCriterion("`client_secret` =", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotEqualTo(String value) {
            addCriterion("`client_secret` <>", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretGreaterThan(String value) {
            addCriterion("`client_secret` >", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretGreaterThanOrEqualTo(String value) {
            addCriterion("`client_secret` >=", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretLessThan(String value) {
            addCriterion("`client_secret` <", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretLessThanOrEqualTo(String value) {
            addCriterion("`client_secret` <=", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretLike(String value) {
            addCriterion("`client_secret` like", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotLike(String value) {
            addCriterion("`client_secret` not like", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretIn(List<String> values) {
            addCriterion("`client_secret` in", values, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotIn(List<String> values) {
            addCriterion("`client_secret` not in", values, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretBetween(String value1, String value2) {
            addCriterion("`client_secret` between", value1, value2, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotBetween(String value1, String value2) {
            addCriterion("`client_secret` not between", value1, value2, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtIsNull() {
            addCriterion("`client_secret_expires_at` is null");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtIsNotNull() {
            addCriterion("`client_secret_expires_at` is not null");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtEqualTo(LocalDateTime value) {
            addCriterion("`client_secret_expires_at` =", value, "clientSecretExpiresAt");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtNotEqualTo(LocalDateTime value) {
            addCriterion("`client_secret_expires_at` <>", value, "clientSecretExpiresAt");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtGreaterThan(LocalDateTime value) {
            addCriterion("`client_secret_expires_at` >", value, "clientSecretExpiresAt");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`client_secret_expires_at` >=", value, "clientSecretExpiresAt");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtLessThan(LocalDateTime value) {
            addCriterion("`client_secret_expires_at` <", value, "clientSecretExpiresAt");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`client_secret_expires_at` <=", value, "clientSecretExpiresAt");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtIn(List<LocalDateTime> values) {
            addCriterion("`client_secret_expires_at` in", values, "clientSecretExpiresAt");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtNotIn(List<LocalDateTime> values) {
            addCriterion("`client_secret_expires_at` not in", values, "clientSecretExpiresAt");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`client_secret_expires_at` between", value1, value2, "clientSecretExpiresAt");
            return (Criteria) this;
        }

        public Criteria andClientSecretExpiresAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`client_secret_expires_at` not between", value1, value2, "clientSecretExpiresAt");
            return (Criteria) this;
        }

        public Criteria andClientNameIsNull() {
            addCriterion("`client_name` is null");
            return (Criteria) this;
        }

        public Criteria andClientNameIsNotNull() {
            addCriterion("`client_name` is not null");
            return (Criteria) this;
        }

        public Criteria andClientNameEqualTo(String value) {
            addCriterion("`client_name` =", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotEqualTo(String value) {
            addCriterion("`client_name` <>", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameGreaterThan(String value) {
            addCriterion("`client_name` >", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameGreaterThanOrEqualTo(String value) {
            addCriterion("`client_name` >=", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLessThan(String value) {
            addCriterion("`client_name` <", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLessThanOrEqualTo(String value) {
            addCriterion("`client_name` <=", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLike(String value) {
            addCriterion("`client_name` like", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotLike(String value) {
            addCriterion("`client_name` not like", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameIn(List<String> values) {
            addCriterion("`client_name` in", values, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotIn(List<String> values) {
            addCriterion("`client_name` not in", values, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameBetween(String value1, String value2) {
            addCriterion("`client_name` between", value1, value2, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotBetween(String value1, String value2) {
            addCriterion("`client_name` not between", value1, value2, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsIsNull() {
            addCriterion("`client_authentication_methods` is null");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsIsNotNull() {
            addCriterion("`client_authentication_methods` is not null");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsEqualTo(String value) {
            addCriterion("`client_authentication_methods` =", value, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsNotEqualTo(String value) {
            addCriterion("`client_authentication_methods` <>", value, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsGreaterThan(String value) {
            addCriterion("`client_authentication_methods` >", value, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsGreaterThanOrEqualTo(String value) {
            addCriterion("`client_authentication_methods` >=", value, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsLessThan(String value) {
            addCriterion("`client_authentication_methods` <", value, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsLessThanOrEqualTo(String value) {
            addCriterion("`client_authentication_methods` <=", value, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsLike(String value) {
            addCriterion("`client_authentication_methods` like", value, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsNotLike(String value) {
            addCriterion("`client_authentication_methods` not like", value, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsIn(List<String> values) {
            addCriterion("`client_authentication_methods` in", values, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsNotIn(List<String> values) {
            addCriterion("`client_authentication_methods` not in", values, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsBetween(String value1, String value2) {
            addCriterion("`client_authentication_methods` between", value1, value2, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andClientAuthenticationMethodsNotBetween(String value1, String value2) {
            addCriterion("`client_authentication_methods` not between", value1, value2, "clientAuthenticationMethods");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesIsNull() {
            addCriterion("`authorization_grant_types` is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesIsNotNull() {
            addCriterion("`authorization_grant_types` is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesEqualTo(String value) {
            addCriterion("`authorization_grant_types` =", value, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesNotEqualTo(String value) {
            addCriterion("`authorization_grant_types` <>", value, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesGreaterThan(String value) {
            addCriterion("`authorization_grant_types` >", value, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesGreaterThanOrEqualTo(String value) {
            addCriterion("`authorization_grant_types` >=", value, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesLessThan(String value) {
            addCriterion("`authorization_grant_types` <", value, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesLessThanOrEqualTo(String value) {
            addCriterion("`authorization_grant_types` <=", value, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesLike(String value) {
            addCriterion("`authorization_grant_types` like", value, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesNotLike(String value) {
            addCriterion("`authorization_grant_types` not like", value, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesIn(List<String> values) {
            addCriterion("`authorization_grant_types` in", values, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesNotIn(List<String> values) {
            addCriterion("`authorization_grant_types` not in", values, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesBetween(String value1, String value2) {
            addCriterion("`authorization_grant_types` between", value1, value2, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypesNotBetween(String value1, String value2) {
            addCriterion("`authorization_grant_types` not between", value1, value2, "authorizationGrantTypes");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisIsNull() {
            addCriterion("`redirect_uris` is null");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisIsNotNull() {
            addCriterion("`redirect_uris` is not null");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisEqualTo(String value) {
            addCriterion("`redirect_uris` =", value, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisNotEqualTo(String value) {
            addCriterion("`redirect_uris` <>", value, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisGreaterThan(String value) {
            addCriterion("`redirect_uris` >", value, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisGreaterThanOrEqualTo(String value) {
            addCriterion("`redirect_uris` >=", value, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisLessThan(String value) {
            addCriterion("`redirect_uris` <", value, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisLessThanOrEqualTo(String value) {
            addCriterion("`redirect_uris` <=", value, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisLike(String value) {
            addCriterion("`redirect_uris` like", value, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisNotLike(String value) {
            addCriterion("`redirect_uris` not like", value, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisIn(List<String> values) {
            addCriterion("`redirect_uris` in", values, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisNotIn(List<String> values) {
            addCriterion("`redirect_uris` not in", values, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisBetween(String value1, String value2) {
            addCriterion("`redirect_uris` between", value1, value2, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andRedirectUrisNotBetween(String value1, String value2) {
            addCriterion("`redirect_uris` not between", value1, value2, "redirectUris");
            return (Criteria) this;
        }

        public Criteria andScopesIsNull() {
            addCriterion("`scopes` is null");
            return (Criteria) this;
        }

        public Criteria andScopesIsNotNull() {
            addCriterion("`scopes` is not null");
            return (Criteria) this;
        }

        public Criteria andScopesEqualTo(String value) {
            addCriterion("`scopes` =", value, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesNotEqualTo(String value) {
            addCriterion("`scopes` <>", value, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesGreaterThan(String value) {
            addCriterion("`scopes` >", value, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesGreaterThanOrEqualTo(String value) {
            addCriterion("`scopes` >=", value, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesLessThan(String value) {
            addCriterion("`scopes` <", value, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesLessThanOrEqualTo(String value) {
            addCriterion("`scopes` <=", value, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesLike(String value) {
            addCriterion("`scopes` like", value, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesNotLike(String value) {
            addCriterion("`scopes` not like", value, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesIn(List<String> values) {
            addCriterion("`scopes` in", values, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesNotIn(List<String> values) {
            addCriterion("`scopes` not in", values, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesBetween(String value1, String value2) {
            addCriterion("`scopes` between", value1, value2, "scopes");
            return (Criteria) this;
        }

        public Criteria andScopesNotBetween(String value1, String value2) {
            addCriterion("`scopes` not between", value1, value2, "scopes");
            return (Criteria) this;
        }

        public Criteria andClientSettingsIsNull() {
            addCriterion("`client_settings` is null");
            return (Criteria) this;
        }

        public Criteria andClientSettingsIsNotNull() {
            addCriterion("`client_settings` is not null");
            return (Criteria) this;
        }

        public Criteria andClientSettingsEqualTo(String value) {
            addCriterion("`client_settings` =", value, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsNotEqualTo(String value) {
            addCriterion("`client_settings` <>", value, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsGreaterThan(String value) {
            addCriterion("`client_settings` >", value, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsGreaterThanOrEqualTo(String value) {
            addCriterion("`client_settings` >=", value, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsLessThan(String value) {
            addCriterion("`client_settings` <", value, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsLessThanOrEqualTo(String value) {
            addCriterion("`client_settings` <=", value, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsLike(String value) {
            addCriterion("`client_settings` like", value, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsNotLike(String value) {
            addCriterion("`client_settings` not like", value, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsIn(List<String> values) {
            addCriterion("`client_settings` in", values, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsNotIn(List<String> values) {
            addCriterion("`client_settings` not in", values, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsBetween(String value1, String value2) {
            addCriterion("`client_settings` between", value1, value2, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andClientSettingsNotBetween(String value1, String value2) {
            addCriterion("`client_settings` not between", value1, value2, "clientSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsIsNull() {
            addCriterion("`token_settings` is null");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsIsNotNull() {
            addCriterion("`token_settings` is not null");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsEqualTo(String value) {
            addCriterion("`token_settings` =", value, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsNotEqualTo(String value) {
            addCriterion("`token_settings` <>", value, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsGreaterThan(String value) {
            addCriterion("`token_settings` >", value, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsGreaterThanOrEqualTo(String value) {
            addCriterion("`token_settings` >=", value, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsLessThan(String value) {
            addCriterion("`token_settings` <", value, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsLessThanOrEqualTo(String value) {
            addCriterion("`token_settings` <=", value, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsLike(String value) {
            addCriterion("`token_settings` like", value, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsNotLike(String value) {
            addCriterion("`token_settings` not like", value, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsIn(List<String> values) {
            addCriterion("`token_settings` in", values, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsNotIn(List<String> values) {
            addCriterion("`token_settings` not in", values, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsBetween(String value1, String value2) {
            addCriterion("`token_settings` between", value1, value2, "tokenSettings");
            return (Criteria) this;
        }

        public Criteria andTokenSettingsNotBetween(String value1, String value2) {
            addCriterion("`token_settings` not between", value1, value2, "tokenSettings");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}