package cc.rits.membership.console.iam.infrastructure.db.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class Oauth2AuthorizationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public Oauth2AuthorizationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("`id` like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("`id` not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdIsNull() {
            addCriterion("`registered_client_id` is null");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdIsNotNull() {
            addCriterion("`registered_client_id` is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdEqualTo(String value) {
            addCriterion("`registered_client_id` =", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdNotEqualTo(String value) {
            addCriterion("`registered_client_id` <>", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdGreaterThan(String value) {
            addCriterion("`registered_client_id` >", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("`registered_client_id` >=", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdLessThan(String value) {
            addCriterion("`registered_client_id` <", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdLessThanOrEqualTo(String value) {
            addCriterion("`registered_client_id` <=", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdLike(String value) {
            addCriterion("`registered_client_id` like", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdNotLike(String value) {
            addCriterion("`registered_client_id` not like", value, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdIn(List<String> values) {
            addCriterion("`registered_client_id` in", values, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdNotIn(List<String> values) {
            addCriterion("`registered_client_id` not in", values, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdBetween(String value1, String value2) {
            addCriterion("`registered_client_id` between", value1, value2, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andRegisteredClientIdNotBetween(String value1, String value2) {
            addCriterion("`registered_client_id` not between", value1, value2, "registeredClientId");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameIsNull() {
            addCriterion("`principal_name` is null");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameIsNotNull() {
            addCriterion("`principal_name` is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameEqualTo(String value) {
            addCriterion("`principal_name` =", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotEqualTo(String value) {
            addCriterion("`principal_name` <>", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameGreaterThan(String value) {
            addCriterion("`principal_name` >", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameGreaterThanOrEqualTo(String value) {
            addCriterion("`principal_name` >=", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameLessThan(String value) {
            addCriterion("`principal_name` <", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameLessThanOrEqualTo(String value) {
            addCriterion("`principal_name` <=", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameLike(String value) {
            addCriterion("`principal_name` like", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotLike(String value) {
            addCriterion("`principal_name` not like", value, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameIn(List<String> values) {
            addCriterion("`principal_name` in", values, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotIn(List<String> values) {
            addCriterion("`principal_name` not in", values, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameBetween(String value1, String value2) {
            addCriterion("`principal_name` between", value1, value2, "principalName");
            return (Criteria) this;
        }

        public Criteria andPrincipalNameNotBetween(String value1, String value2) {
            addCriterion("`principal_name` not between", value1, value2, "principalName");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeIsNull() {
            addCriterion("`authorization_grant_type` is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeIsNotNull() {
            addCriterion("`authorization_grant_type` is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeEqualTo(String value) {
            addCriterion("`authorization_grant_type` =", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeNotEqualTo(String value) {
            addCriterion("`authorization_grant_type` <>", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeGreaterThan(String value) {
            addCriterion("`authorization_grant_type` >", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`authorization_grant_type` >=", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeLessThan(String value) {
            addCriterion("`authorization_grant_type` <", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeLessThanOrEqualTo(String value) {
            addCriterion("`authorization_grant_type` <=", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeLike(String value) {
            addCriterion("`authorization_grant_type` like", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeNotLike(String value) {
            addCriterion("`authorization_grant_type` not like", value, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeIn(List<String> values) {
            addCriterion("`authorization_grant_type` in", values, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeNotIn(List<String> values) {
            addCriterion("`authorization_grant_type` not in", values, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeBetween(String value1, String value2) {
            addCriterion("`authorization_grant_type` between", value1, value2, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAuthorizationGrantTypeNotBetween(String value1, String value2) {
            addCriterion("`authorization_grant_type` not between", value1, value2, "authorizationGrantType");
            return (Criteria) this;
        }

        public Criteria andAttributesIsNull() {
            addCriterion("`attributes` is null");
            return (Criteria) this;
        }

        public Criteria andAttributesIsNotNull() {
            addCriterion("`attributes` is not null");
            return (Criteria) this;
        }

        public Criteria andAttributesEqualTo(String value) {
            addCriterion("`attributes` =", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotEqualTo(String value) {
            addCriterion("`attributes` <>", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesGreaterThan(String value) {
            addCriterion("`attributes` >", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesGreaterThanOrEqualTo(String value) {
            addCriterion("`attributes` >=", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesLessThan(String value) {
            addCriterion("`attributes` <", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesLessThanOrEqualTo(String value) {
            addCriterion("`attributes` <=", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesLike(String value) {
            addCriterion("`attributes` like", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotLike(String value) {
            addCriterion("`attributes` not like", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesIn(List<String> values) {
            addCriterion("`attributes` in", values, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotIn(List<String> values) {
            addCriterion("`attributes` not in", values, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesBetween(String value1, String value2) {
            addCriterion("`attributes` between", value1, value2, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotBetween(String value1, String value2) {
            addCriterion("`attributes` not between", value1, value2, "attributes");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("`state` like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("`state` not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtIsNull() {
            addCriterion("`authorization_code_issued_at` is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtIsNotNull() {
            addCriterion("`authorization_code_issued_at` is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtEqualTo(LocalDateTime value) {
            addCriterion("`authorization_code_issued_at` =", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtNotEqualTo(LocalDateTime value) {
            addCriterion("`authorization_code_issued_at` <>", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtGreaterThan(LocalDateTime value) {
            addCriterion("`authorization_code_issued_at` >", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`authorization_code_issued_at` >=", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtLessThan(LocalDateTime value) {
            addCriterion("`authorization_code_issued_at` <", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`authorization_code_issued_at` <=", value, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtIn(List<LocalDateTime> values) {
            addCriterion("`authorization_code_issued_at` in", values, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtNotIn(List<LocalDateTime> values) {
            addCriterion("`authorization_code_issued_at` not in", values, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`authorization_code_issued_at` between", value1, value2, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIssuedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`authorization_code_issued_at` not between", value1, value2, "authorizationCodeIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtIsNull() {
            addCriterion("`authorization_code_expires_at` is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtIsNotNull() {
            addCriterion("`authorization_code_expires_at` is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtEqualTo(LocalDateTime value) {
            addCriterion("`authorization_code_expires_at` =", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtNotEqualTo(LocalDateTime value) {
            addCriterion("`authorization_code_expires_at` <>", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtGreaterThan(LocalDateTime value) {
            addCriterion("`authorization_code_expires_at` >", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`authorization_code_expires_at` >=", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtLessThan(LocalDateTime value) {
            addCriterion("`authorization_code_expires_at` <", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`authorization_code_expires_at` <=", value, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtIn(List<LocalDateTime> values) {
            addCriterion("`authorization_code_expires_at` in", values, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtNotIn(List<LocalDateTime> values) {
            addCriterion("`authorization_code_expires_at` not in", values, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`authorization_code_expires_at` between", value1, value2, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeExpiresAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`authorization_code_expires_at` not between", value1, value2, "authorizationCodeExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataIsNull() {
            addCriterion("`authorization_code_metadata` is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataIsNotNull() {
            addCriterion("`authorization_code_metadata` is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataEqualTo(String value) {
            addCriterion("`authorization_code_metadata` =", value, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataNotEqualTo(String value) {
            addCriterion("`authorization_code_metadata` <>", value, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataGreaterThan(String value) {
            addCriterion("`authorization_code_metadata` >", value, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataGreaterThanOrEqualTo(String value) {
            addCriterion("`authorization_code_metadata` >=", value, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataLessThan(String value) {
            addCriterion("`authorization_code_metadata` <", value, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataLessThanOrEqualTo(String value) {
            addCriterion("`authorization_code_metadata` <=", value, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataLike(String value) {
            addCriterion("`authorization_code_metadata` like", value, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataNotLike(String value) {
            addCriterion("`authorization_code_metadata` not like", value, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataIn(List<String> values) {
            addCriterion("`authorization_code_metadata` in", values, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataNotIn(List<String> values) {
            addCriterion("`authorization_code_metadata` not in", values, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataBetween(String value1, String value2) {
            addCriterion("`authorization_code_metadata` between", value1, value2, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeMetadataNotBetween(String value1, String value2) {
            addCriterion("`authorization_code_metadata` not between", value1, value2, "authorizationCodeMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtIsNull() {
            addCriterion("`access_token_issued_at` is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtIsNotNull() {
            addCriterion("`access_token_issued_at` is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtEqualTo(LocalDateTime value) {
            addCriterion("`access_token_issued_at` =", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtNotEqualTo(LocalDateTime value) {
            addCriterion("`access_token_issued_at` <>", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtGreaterThan(LocalDateTime value) {
            addCriterion("`access_token_issued_at` >", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`access_token_issued_at` >=", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtLessThan(LocalDateTime value) {
            addCriterion("`access_token_issued_at` <", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`access_token_issued_at` <=", value, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtIn(List<LocalDateTime> values) {
            addCriterion("`access_token_issued_at` in", values, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtNotIn(List<LocalDateTime> values) {
            addCriterion("`access_token_issued_at` not in", values, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`access_token_issued_at` between", value1, value2, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIssuedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`access_token_issued_at` not between", value1, value2, "accessTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtIsNull() {
            addCriterion("`access_token_expires_at` is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtIsNotNull() {
            addCriterion("`access_token_expires_at` is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtEqualTo(LocalDateTime value) {
            addCriterion("`access_token_expires_at` =", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtNotEqualTo(LocalDateTime value) {
            addCriterion("`access_token_expires_at` <>", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtGreaterThan(LocalDateTime value) {
            addCriterion("`access_token_expires_at` >", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`access_token_expires_at` >=", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtLessThan(LocalDateTime value) {
            addCriterion("`access_token_expires_at` <", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`access_token_expires_at` <=", value, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtIn(List<LocalDateTime> values) {
            addCriterion("`access_token_expires_at` in", values, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtNotIn(List<LocalDateTime> values) {
            addCriterion("`access_token_expires_at` not in", values, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`access_token_expires_at` between", value1, value2, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenExpiresAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`access_token_expires_at` not between", value1, value2, "accessTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataIsNull() {
            addCriterion("`access_token_metadata` is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataIsNotNull() {
            addCriterion("`access_token_metadata` is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataEqualTo(String value) {
            addCriterion("`access_token_metadata` =", value, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataNotEqualTo(String value) {
            addCriterion("`access_token_metadata` <>", value, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataGreaterThan(String value) {
            addCriterion("`access_token_metadata` >", value, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataGreaterThanOrEqualTo(String value) {
            addCriterion("`access_token_metadata` >=", value, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataLessThan(String value) {
            addCriterion("`access_token_metadata` <", value, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataLessThanOrEqualTo(String value) {
            addCriterion("`access_token_metadata` <=", value, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataLike(String value) {
            addCriterion("`access_token_metadata` like", value, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataNotLike(String value) {
            addCriterion("`access_token_metadata` not like", value, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataIn(List<String> values) {
            addCriterion("`access_token_metadata` in", values, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataNotIn(List<String> values) {
            addCriterion("`access_token_metadata` not in", values, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataBetween(String value1, String value2) {
            addCriterion("`access_token_metadata` between", value1, value2, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenMetadataNotBetween(String value1, String value2) {
            addCriterion("`access_token_metadata` not between", value1, value2, "accessTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeIsNull() {
            addCriterion("`access_token_type` is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeIsNotNull() {
            addCriterion("`access_token_type` is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeEqualTo(String value) {
            addCriterion("`access_token_type` =", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotEqualTo(String value) {
            addCriterion("`access_token_type` <>", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeGreaterThan(String value) {
            addCriterion("`access_token_type` >", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`access_token_type` >=", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeLessThan(String value) {
            addCriterion("`access_token_type` <", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeLessThanOrEqualTo(String value) {
            addCriterion("`access_token_type` <=", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeLike(String value) {
            addCriterion("`access_token_type` like", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotLike(String value) {
            addCriterion("`access_token_type` not like", value, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeIn(List<String> values) {
            addCriterion("`access_token_type` in", values, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotIn(List<String> values) {
            addCriterion("`access_token_type` not in", values, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeBetween(String value1, String value2) {
            addCriterion("`access_token_type` between", value1, value2, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenTypeNotBetween(String value1, String value2) {
            addCriterion("`access_token_type` not between", value1, value2, "accessTokenType");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesIsNull() {
            addCriterion("`access_token_scopes` is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesIsNotNull() {
            addCriterion("`access_token_scopes` is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesEqualTo(String value) {
            addCriterion("`access_token_scopes` =", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotEqualTo(String value) {
            addCriterion("`access_token_scopes` <>", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesGreaterThan(String value) {
            addCriterion("`access_token_scopes` >", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesGreaterThanOrEqualTo(String value) {
            addCriterion("`access_token_scopes` >=", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesLessThan(String value) {
            addCriterion("`access_token_scopes` <", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesLessThanOrEqualTo(String value) {
            addCriterion("`access_token_scopes` <=", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesLike(String value) {
            addCriterion("`access_token_scopes` like", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotLike(String value) {
            addCriterion("`access_token_scopes` not like", value, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesIn(List<String> values) {
            addCriterion("`access_token_scopes` in", values, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotIn(List<String> values) {
            addCriterion("`access_token_scopes` not in", values, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesBetween(String value1, String value2) {
            addCriterion("`access_token_scopes` between", value1, value2, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andAccessTokenScopesNotBetween(String value1, String value2) {
            addCriterion("`access_token_scopes` not between", value1, value2, "accessTokenScopes");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtIsNull() {
            addCriterion("`oidc_id_token_issued_at` is null");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtIsNotNull() {
            addCriterion("`oidc_id_token_issued_at` is not null");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtEqualTo(LocalDateTime value) {
            addCriterion("`oidc_id_token_issued_at` =", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtNotEqualTo(LocalDateTime value) {
            addCriterion("`oidc_id_token_issued_at` <>", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtGreaterThan(LocalDateTime value) {
            addCriterion("`oidc_id_token_issued_at` >", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`oidc_id_token_issued_at` >=", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtLessThan(LocalDateTime value) {
            addCriterion("`oidc_id_token_issued_at` <", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`oidc_id_token_issued_at` <=", value, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtIn(List<LocalDateTime> values) {
            addCriterion("`oidc_id_token_issued_at` in", values, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtNotIn(List<LocalDateTime> values) {
            addCriterion("`oidc_id_token_issued_at` not in", values, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`oidc_id_token_issued_at` between", value1, value2, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenIssuedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`oidc_id_token_issued_at` not between", value1, value2, "oidcIdTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtIsNull() {
            addCriterion("`oidc_id_token_expires_at` is null");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtIsNotNull() {
            addCriterion("`oidc_id_token_expires_at` is not null");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtEqualTo(LocalDateTime value) {
            addCriterion("`oidc_id_token_expires_at` =", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtNotEqualTo(LocalDateTime value) {
            addCriterion("`oidc_id_token_expires_at` <>", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtGreaterThan(LocalDateTime value) {
            addCriterion("`oidc_id_token_expires_at` >", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`oidc_id_token_expires_at` >=", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtLessThan(LocalDateTime value) {
            addCriterion("`oidc_id_token_expires_at` <", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`oidc_id_token_expires_at` <=", value, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtIn(List<LocalDateTime> values) {
            addCriterion("`oidc_id_token_expires_at` in", values, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtNotIn(List<LocalDateTime> values) {
            addCriterion("`oidc_id_token_expires_at` not in", values, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`oidc_id_token_expires_at` between", value1, value2, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenExpiresAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`oidc_id_token_expires_at` not between", value1, value2, "oidcIdTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataIsNull() {
            addCriterion("`oidc_id_token_metadata` is null");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataIsNotNull() {
            addCriterion("`oidc_id_token_metadata` is not null");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataEqualTo(String value) {
            addCriterion("`oidc_id_token_metadata` =", value, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataNotEqualTo(String value) {
            addCriterion("`oidc_id_token_metadata` <>", value, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataGreaterThan(String value) {
            addCriterion("`oidc_id_token_metadata` >", value, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataGreaterThanOrEqualTo(String value) {
            addCriterion("`oidc_id_token_metadata` >=", value, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataLessThan(String value) {
            addCriterion("`oidc_id_token_metadata` <", value, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataLessThanOrEqualTo(String value) {
            addCriterion("`oidc_id_token_metadata` <=", value, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataLike(String value) {
            addCriterion("`oidc_id_token_metadata` like", value, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataNotLike(String value) {
            addCriterion("`oidc_id_token_metadata` not like", value, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataIn(List<String> values) {
            addCriterion("`oidc_id_token_metadata` in", values, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataNotIn(List<String> values) {
            addCriterion("`oidc_id_token_metadata` not in", values, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataBetween(String value1, String value2) {
            addCriterion("`oidc_id_token_metadata` between", value1, value2, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andOidcIdTokenMetadataNotBetween(String value1, String value2) {
            addCriterion("`oidc_id_token_metadata` not between", value1, value2, "oidcIdTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtIsNull() {
            addCriterion("`refresh_token_issued_at` is null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtIsNotNull() {
            addCriterion("`refresh_token_issued_at` is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtEqualTo(LocalDateTime value) {
            addCriterion("`refresh_token_issued_at` =", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtNotEqualTo(LocalDateTime value) {
            addCriterion("`refresh_token_issued_at` <>", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtGreaterThan(LocalDateTime value) {
            addCriterion("`refresh_token_issued_at` >", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`refresh_token_issued_at` >=", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtLessThan(LocalDateTime value) {
            addCriterion("`refresh_token_issued_at` <", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`refresh_token_issued_at` <=", value, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtIn(List<LocalDateTime> values) {
            addCriterion("`refresh_token_issued_at` in", values, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtNotIn(List<LocalDateTime> values) {
            addCriterion("`refresh_token_issued_at` not in", values, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`refresh_token_issued_at` between", value1, value2, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIssuedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`refresh_token_issued_at` not between", value1, value2, "refreshTokenIssuedAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtIsNull() {
            addCriterion("`refresh_token_expires_at` is null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtIsNotNull() {
            addCriterion("`refresh_token_expires_at` is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtEqualTo(LocalDateTime value) {
            addCriterion("`refresh_token_expires_at` =", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtNotEqualTo(LocalDateTime value) {
            addCriterion("`refresh_token_expires_at` <>", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtGreaterThan(LocalDateTime value) {
            addCriterion("`refresh_token_expires_at` >", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`refresh_token_expires_at` >=", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtLessThan(LocalDateTime value) {
            addCriterion("`refresh_token_expires_at` <", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`refresh_token_expires_at` <=", value, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtIn(List<LocalDateTime> values) {
            addCriterion("`refresh_token_expires_at` in", values, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtNotIn(List<LocalDateTime> values) {
            addCriterion("`refresh_token_expires_at` not in", values, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`refresh_token_expires_at` between", value1, value2, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenExpiresAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`refresh_token_expires_at` not between", value1, value2, "refreshTokenExpiresAt");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataIsNull() {
            addCriterion("`refresh_token_metadata` is null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataIsNotNull() {
            addCriterion("`refresh_token_metadata` is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataEqualTo(String value) {
            addCriterion("`refresh_token_metadata` =", value, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataNotEqualTo(String value) {
            addCriterion("`refresh_token_metadata` <>", value, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataGreaterThan(String value) {
            addCriterion("`refresh_token_metadata` >", value, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataGreaterThanOrEqualTo(String value) {
            addCriterion("`refresh_token_metadata` >=", value, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataLessThan(String value) {
            addCriterion("`refresh_token_metadata` <", value, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataLessThanOrEqualTo(String value) {
            addCriterion("`refresh_token_metadata` <=", value, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataLike(String value) {
            addCriterion("`refresh_token_metadata` like", value, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataNotLike(String value) {
            addCriterion("`refresh_token_metadata` not like", value, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataIn(List<String> values) {
            addCriterion("`refresh_token_metadata` in", values, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataNotIn(List<String> values) {
            addCriterion("`refresh_token_metadata` not in", values, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataBetween(String value1, String value2) {
            addCriterion("`refresh_token_metadata` between", value1, value2, "refreshTokenMetadata");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenMetadataNotBetween(String value1, String value2) {
            addCriterion("`refresh_token_metadata` not between", value1, value2, "refreshTokenMetadata");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_authorization
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}