package cc.rits.membership.console.iam.infrastructure.db.entity;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Oauth2RegisteredClient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_id
     *
     * @mbg.generated
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_id_issued_at
     *
     * @mbg.generated
     */
    private LocalDateTime clientIdIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_secret
     *
     * @mbg.generated
     */
    private String clientSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_secret_expires_at
     *
     * @mbg.generated
     */
    private LocalDateTime clientSecretExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_name
     *
     * @mbg.generated
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_authentication_methods
     *
     * @mbg.generated
     */
    private String clientAuthenticationMethods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.authorization_grant_types
     *
     * @mbg.generated
     */
    private String authorizationGrantTypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.redirect_uris
     *
     * @mbg.generated
     */
    private String redirectUris;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.scopes
     *
     * @mbg.generated
     */
    private String scopes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.client_settings
     *
     * @mbg.generated
     */
    private String clientSettings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_registered_client.token_settings
     *
     * @mbg.generated
     */
    private String tokenSettings;
}