package cc.rits.membership.console.iam.infrastructure.db.entity;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Oauth2Authorization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.registered_client_id
     *
     * @mbg.generated
     */
    private String registeredClientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.principal_name
     *
     * @mbg.generated
     */
    private String principalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorization_grant_type
     *
     * @mbg.generated
     */
    private String authorizationGrantType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.attributes
     *
     * @mbg.generated
     */
    private String attributes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorization_code_issued_at
     *
     * @mbg.generated
     */
    private LocalDateTime authorizationCodeIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorization_code_expires_at
     *
     * @mbg.generated
     */
    private LocalDateTime authorizationCodeExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorization_code_metadata
     *
     * @mbg.generated
     */
    private String authorizationCodeMetadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_issued_at
     *
     * @mbg.generated
     */
    private LocalDateTime accessTokenIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_expires_at
     *
     * @mbg.generated
     */
    private LocalDateTime accessTokenExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_metadata
     *
     * @mbg.generated
     */
    private String accessTokenMetadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_type
     *
     * @mbg.generated
     */
    private String accessTokenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_scopes
     *
     * @mbg.generated
     */
    private String accessTokenScopes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.oidc_id_token_issued_at
     *
     * @mbg.generated
     */
    private LocalDateTime oidcIdTokenIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.oidc_id_token_expires_at
     *
     * @mbg.generated
     */
    private LocalDateTime oidcIdTokenExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.oidc_id_token_metadata
     *
     * @mbg.generated
     */
    private String oidcIdTokenMetadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.refresh_token_issued_at
     *
     * @mbg.generated
     */
    private LocalDateTime refreshTokenIssuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.refresh_token_expires_at
     *
     * @mbg.generated
     */
    private LocalDateTime refreshTokenExpiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.refresh_token_metadata
     *
     * @mbg.generated
     */
    private String refreshTokenMetadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.authorization_code_value
     *
     * @mbg.generated
     */
    private byte[] authorizationCodeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.access_token_value
     *
     * @mbg.generated
     */
    private byte[] accessTokenValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.oidc_id_token_value
     *
     * @mbg.generated
     */
    private byte[] oidcIdTokenValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth2_authorization.refresh_token_value
     *
     * @mbg.generated
     */
    private byte[] refreshTokenValue;
}