package cc.rits.membership.console.iam.infrastructure.db.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class RUserGroupUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_group_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_group_user.user_group_id
     *
     * @mbg.generated
     */
    private Integer userGroupId;
}