package cc.rits.membership.console.iam.infrastructure.db.mapper.base;

import cc.rits.membership.console.iam.infrastructure.db.entity.Oauth2RegisteredClient;
import cc.rits.membership.console.iam.infrastructure.db.entity.Oauth2RegisteredClientExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface Oauth2RegisteredClientBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    long countByExample(Oauth2RegisteredClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    int deleteByExample(Oauth2RegisteredClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    int insert(Oauth2RegisteredClient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    int insertSelective(Oauth2RegisteredClient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    List<Oauth2RegisteredClient> selectByExampleWithRowbounds(Oauth2RegisteredClientExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    List<Oauth2RegisteredClient> selectByExample(Oauth2RegisteredClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    Oauth2RegisteredClient selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Oauth2RegisteredClient row, @Param("example") Oauth2RegisteredClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Oauth2RegisteredClient row, @Param("example") Oauth2RegisteredClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Oauth2RegisteredClient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_registered_client
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Oauth2RegisteredClient row);
}