package cc.rits.membership.console.iam.infrastructure.db.mapper.base;

import cc.rits.membership.console.iam.infrastructure.db.entity.Oauth2Authorization;
import cc.rits.membership.console.iam.infrastructure.db.entity.Oauth2AuthorizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface Oauth2AuthorizationBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    long countByExample(Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    int deleteByExample(Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    int insert(Oauth2Authorization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    int insertSelective(Oauth2Authorization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    List<Oauth2Authorization> selectByExampleWithBLOBsWithRowbounds(Oauth2AuthorizationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    List<Oauth2Authorization> selectByExampleWithBLOBs(Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    List<Oauth2Authorization> selectByExampleWithRowbounds(Oauth2AuthorizationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    List<Oauth2Authorization> selectByExample(Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    Oauth2Authorization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Oauth2Authorization row, @Param("example") Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") Oauth2Authorization row, @Param("example") Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Oauth2Authorization row, @Param("example") Oauth2AuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Oauth2Authorization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Oauth2Authorization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_authorization
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Oauth2Authorization row);
}