package cc.rits.membership.console.iam.infrastructure.db.mapper.base;

import cc.rits.membership.console.iam.infrastructure.db.entity.PasswordResetToken;
import cc.rits.membership.console.iam.infrastructure.db.entity.PasswordResetTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PasswordResetTokenBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    long countByExample(PasswordResetTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    int deleteByExample(PasswordResetTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    int insert(PasswordResetToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    int insertSelective(PasswordResetToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    List<PasswordResetToken> selectByExampleWithRowbounds(PasswordResetTokenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    List<PasswordResetToken> selectByExample(PasswordResetTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    PasswordResetToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PasswordResetToken row, @Param("example") PasswordResetTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PasswordResetToken row, @Param("example") PasswordResetTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PasswordResetToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password_reset_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PasswordResetToken row);
}