package cc.rits.membership.console.iam.infrastructure.db.mapper.base;

import cc.rits.membership.console.iam.infrastructure.db.entity.RUserGroupUser;
import cc.rits.membership.console.iam.infrastructure.db.entity.RUserGroupUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface RUserGroupUserBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_group_user
     *
     * @mbg.generated
     */
    long countByExample(RUserGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_group_user
     *
     * @mbg.generated
     */
    int deleteByExample(RUserGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_group_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("userGroupId") Integer userGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_group_user
     *
     * @mbg.generated
     */
    int insert(RUserGroupUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_group_user
     *
     * @mbg.generated
     */
    int insertSelective(RUserGroupUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_group_user
     *
     * @mbg.generated
     */
    List<RUserGroupUser> selectByExampleWithRowbounds(RUserGroupUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_group_user
     *
     * @mbg.generated
     */
    List<RUserGroupUser> selectByExample(RUserGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_group_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") RUserGroupUser row, @Param("example") RUserGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_group_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") RUserGroupUser row, @Param("example") RUserGroupUserExample example);
}